### ISSUE TITLE
Save image (using github API)

### ISSUE THREAD

**Issue by assafg** [tikalk/hr-emplyee-profile-manager#8]
If there is a picture - add it to git to to the correct location (https://github.com/tikalk/tikal_jekyll_website/tree/master/_assets/images/pictures/) 
Allow rename picture according to login name.
Allow load picture blob for presenting it

**Comment by urrri** [comment]
PR #23 allows save/read images.
Please integrate

**Comment by urrri** [comment]
Served now by cloudinary
